# Site settings
title: Flynn Bundy
description: A blog about lorem ipsum dolor sit amet
baseurl: "/bundyfx.github.io"
url: "https://flynnbundy.com/"
enforce_ssl: flynnbundy.com
#force-https: True
# User settings

username: Flynn Bundy
user_title: Software Engineer
email: flynn.sbundy@gmail.com
twitter_username: bundyfx
github_username:  bundyfx
youtube: https://www.youtube.com/channel/UCKZy6c6KewxX_SnfYpOMxLg

# Google-analytics
google-analytics:
  id: "UA-88009769-1"

exclude: ['package.json', 'src' , 'node_modules']
