
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://bundyfx.github.io/"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /bundyfx-blog

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Flynn Bundy"
title: "{ Flynn Bundy }"
description: "Blog and website of Flynn Bundy. Speaker, Blogger, Coder. A Microsoft Cloud and Datacenter MVP interested in all things automated."
keywords: "bundy, flynn, personal, jekyll, theme"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "First, solve the problem. Then, write the code."
  - text: "The cheapest, fastest, and most reliable components are those that aren’t there."

me-img: "/img/author.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: False

post-preview-words: 95

paginate: 10

email-share: True
twitter-share: True
linkedin-share: True

disqus-shortname: "flynnbundy"

syntax-highlight: True

############
# Timeline #
############

###########
# Contact #
###########

email: "flynn.sbundy@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Flynn is a lover of all things automated. His primary interest is on cutting edge technologies surrounding DevOps related tools."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/fbundy"
  - title: "twitter"
    url: "https://twitter.com/Bundyfx"
  - title: "github"
    url: "https://github.com/bundyfx"


############
# 404 page #
############

404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
