# Site settings
title: Flynn Bundy
description: A blog about lorem ipsum dolor sit amet
baseurl: "/bundyfx.github.io"
url: "https://flynnbundy.com"

# User settings
username: Anon Developer
user_description:
user_title: Software Engineer
email: flynn.sbundy@gmail.com
twitter_username: bundyfx
github_username:  bundyfx

# Google-analytics
google-analytics:
  id: "UA-88009769-1"

exclude: ['package.json', 'src' , 'node_modules']
