# Site settings
title: Flynn Bundy
description: A blog about lorem ipsum dolor sit amet
baseurl: "/bundyfx.github.io"
url: "https://flynnbundy.com/"
enforce_ssl: flynnbundy.com
# User settings

force-https: True
username: Flynn Bundy
user_description: A guy
user_title: Software Engineer
email: flynn.sbundy@gmail.com
twitter_username: bundyfx
github_username:  bundyfx

# Google-analytics
google-analytics:
  id: "UA-88009769-1"

exclude: ['package.json', 'src' , 'node_modules']
